//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VemDoBem.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VemDoBem.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cep do endereço deve ser informado..
        /// </summary>
        public static string CepVazio {
            get {
                return ResourceManager.GetString("CepVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da experência não pode exceder os 250 carcteres..
        /// </summary>
        public static string DescricaoExperienciaMaiorQuePermitido {
            get {
                return ResourceManager.GetString("DescricaoExperienciaMaiorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da experência deve possuir o mínimo de 10 caracteres..
        /// </summary>
        public static string DescricaoExperienciaMenorQuePermitido {
            get {
                return ResourceManager.GetString("DescricaoExperienciaMenorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da experiência deve ser informada..
        /// </summary>
        public static string DescricaoExperienciaVazia {
            get {
                return ResourceManager.GetString("DescricaoExperienciaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da instituição não pode exceder os 250 carcteres..
        /// </summary>
        public static string DescricaoInstituicaoMaiorQuePermitido {
            get {
                return ResourceManager.GetString("DescricaoInstituicaoMaiorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da instituição deve possuir o mínimo de 10 caracteres..
        /// </summary>
        public static string DescricaoInstituicaoMenorQuePermitido {
            get {
                return ResourceManager.GetString("DescricaoInstituicaoMenorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da instituição deve ser informada..
        /// </summary>
        public static string DescricaoInstituicaoVazio {
            get {
                return ResourceManager.GetString("DescricaoInstituicaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve ser informado em um formato válido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário deve ser informado..
        /// </summary>
        public static string EmailUsuarioVazio {
            get {
                return ResourceManager.GetString("EmailUsuarioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço deve ser informado..
        /// </summary>
        public static string EnderecoVazio {
            get {
                return ResourceManager.GetString("EnderecoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário responsável deve ser preenchido..
        /// </summary>
        public static string IdUsuarioResponsavelVazio {
            get {
                return ResourceManager.GetString("IdUsuarioResponsavelVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O município do endereço deve ser informado..
        /// </summary>
        public static string MunicipioVazio {
            get {
                return ResourceManager.GetString("MunicipioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da instituição não pode exceder os 120 carcteres..
        /// </summary>
        public static string NomeInstituicaoMaiorQuePermitido {
            get {
                return ResourceManager.GetString("NomeInstituicaoMaiorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da instituição deve possuir o mínimo de 10 caracteres..
        /// </summary>
        public static string NomeInstituicaoMenorQuePermitido {
            get {
                return ResourceManager.GetString("NomeInstituicaoMenorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da instituição deve ser informado..
        /// </summary>
        public static string NomeInstituicaoVazio {
            get {
                return ResourceManager.GetString("NomeInstituicaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode exceder os 80 carcteres..
        /// </summary>
        public static string NomeUsuarioMaiorQuePermitido {
            get {
                return ResourceManager.GetString("NomeUsuarioMaiorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário deve possuir o mínimo de 10 caracteres. .
        /// </summary>
        public static string NomeUsuarioMenorQuePermitido {
            get {
                return ResourceManager.GetString("NomeUsuarioMenorQuePermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado..
        /// </summary>
        public static string NomeUsuarioVazio {
            get {
                return ResourceManager.GetString("NomeUsuarioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rua do endereço deve ser informada..
        /// </summary>
        public static string RuaVazia {
            get {
                return ResourceManager.GetString("RuaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 8 caracteres, contendo maiúsculas, minúsculas numéricos e caracteres especiais..
        /// </summary>
        public static string SenhaUsuarioInvalida {
            get {
                return ResourceManager.GetString("SenhaUsuarioInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ser informada..
        /// </summary>
        public static string SenhaUsuarioVazia {
            get {
                return ResourceManager.GetString("SenhaUsuarioVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cep deve conter exatamento 8 caracteres..
        /// </summary>
        public static string TamanhoDoCepInválido {
            get {
                return ResourceManager.GetString("TamanhoDoCepInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de trabalho deve ser informado..
        /// </summary>
        public static string TipoDeTrabalhoVazio {
            get {
                return ResourceManager.GetString("TipoDeTrabalhoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado do endereço deve ser informado..
        /// </summary>
        public static string UfVazio {
            get {
                return ResourceManager.GetString("UfVazio", resourceCulture);
            }
        }
    }
}
