//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VemDoBem.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VemDoBem.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cep do endereço deve ser informado..
        /// </summary>
        public static string CepVazio {
            get {
                return ResourceManager.GetString("CepVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O município do endereço deve ser preenchido..
        /// </summary>
        public static string MunicipioVazio {
            get {
                return ResourceManager.GetString("MunicipioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rua do endereço deve ser informada..
        /// </summary>
        public static string RuaVazia {
            get {
                return ResourceManager.GetString("RuaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cep deve conter exatamento 8 caracteres..
        /// </summary>
        public static string TamanhoDoCepInválido {
            get {
                return ResourceManager.GetString("TamanhoDoCepInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado do endereço deve ser preenchido..
        /// </summary>
        public static string UfVazio {
            get {
                return ResourceManager.GetString("UfVazio", resourceCulture);
            }
        }
    }
}
