FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build
WORKDIR /src
COPY ["src/VemDoBem.Api/VemDoBem.Api.csproj", "VemDoBem.Api/"]
COPY ["src/VemDoBem.Infra/VemDoBem.Infra.csproj", "VemDoBem.Infra/"]
COPY ["src/VemDoBem.Domain/VemDoBem.Domain.csproj", "VemDoBem.Domain/"]
RUN dotnet restore "./VemDoBem.Api/VemDoBem.Api.csproj"
COPY . .
WORKDIR "/src/VemDoBem.Api"
RUN dotnet build "VemDoBem.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "VemDoBem.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VemDoBem.Api.dll"]
