name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:      
      DOCKER_TARGET_PLATFORM: linux/arm/v7  

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/VemDoBem.Api/VemDoBem.Api.sln
    - name: Build
      run: dotnet build src/VemDoBem.Api/VemDoBem.Api.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/VemDoBem.Api/VemDoBem.Api.sln --no-restore --verbosity normal
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
    - name: Build do container e push no docker hub
      run: |
        docker build . --file src/VemDoBem.Api/VemDoBem.Api/Dockerfile-pi --tag frbatist/vemdobem.api-arm32:latest
        docker tag frbatist/vemdobem.api-arm32:latest frbatist/vemdobem.api-arm32:$(date +%s)
        docker push frbatistvemdobem.api-arm32
