name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/VemDoBem.Api.sln
    - name: Build
      run: dotnet build src/VemDoBem.Api.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/VemDoBem.Api.sln --no-restore --verbosity normal        
    - name: Docker build (Debug)
      uses: docker/build-push-action@v1
      with:
        path: src
        dockerfile: src/Dockerfile-pi
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ secrets.DOCKER_HUB_USER_NAME }}/vemdobem.api-arm32
        build_args: QEMU=true
        add_git_labels: true
        tags: latest
        tag_with_ref: false
        tag_with_sha: false
        push: true
